### PR TITLE
Release 0.0.9

### PR DESCRIPTION
**Pull request by lucab**
Changes:
 * zincati: rework to use std::future
 * zincati: add completion timeout to HTTP requests
 * metrics: stabilize metrics endpoint
 * update-agent: rework steady/polling state
 * docs: add state-machine diagram
 * cargo: relax dependencies micro versions
 * cargo: update all dependencies

Tracker: https://github.com/coreos/zincati/milestone/6

### CODE REVIEW

**Comment by jlebon** [comment]
Related, did you see https://bugzilla.redhat.com/show_bug.cgi?id=1800069 BTW? I think we'll need to sort that out before we can get a release into FCOS.

**Comment by lucab** [comment]
I didn't see that BZ, but Igor was asking for a new release in order to unblock dependencies in Fedora. My understanding is that this should help lowering the pressure, but I don't have a good view/understanding of the whole picture.

/cc @rfairley @ignatenkobrain

**Comment by ignatenkobrain** [comment]
Does this already include pre-release version of actix?

**Comment by lucab** [comment]
@ignatenkobrain not yet in here, as 1) they didn't move out of alpha yet 2) I quickly tried a manual bump, but the API break affects this and code won't build without some further massaging.

**Pull request merged**
