### PR TITLE
Release 0.0.26

### PR DESCRIPTION
**Pull request by cgwalters**
Closes: https://github.com/coreos/zincati/issues/1102

### CODE REVIEW

**Comment by dustymabe** [comment]
do we need to update cargo.lock too?

**Comment by cgwalters** [comment]
> do we need to update cargo.lock too?

Yes!  Thanks for catching that.

**Review by jmarrero — APPROVED** [review]
lgtm

**Comment by dustymabe** [comment]
CI failed on:

```
[2023-10-13T15:33:31.421Z] ERROR: Unable to pull Docker image "registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel8@sha256:cc0c1f250489d250158e649232d0840bb8ffcf7a80cee044106e7c159198ed16". Check if image tag name is spelled correctly.

```

**Comment by jlebon** [comment]
I think the real error is:

> [2023-10-13T15:33:30.094Z] [Warning][coreos-ci/pod-0dd505ec-9f8f-49e8-8a1b-4e058ffef57d-w5v1h-49dzx][Failed] Failed to pull image "registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel8@sha256:cc0c1f250489d250158e649232d0840bb8ffcf7a80cee044106e7c159198ed16": rpc error: code = Unknown desc = reading manifest sha256:cc0c1f250489d250158e649232d0840bb8ffcf7a80cee044106e7c159198ed16 in registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel8: received unexpected HTTP status: 500 Internal Server Error

Hmm, possibly the image is configured as pullthrough and the image is on Quay.io which had errors this morning. (Was doing something unrelated pulling from Quay.io and also hitting HTTP 500 intermittently.)

**Pull request merged**
