### PR TITLE
cargo: update actix to latest version

### PR DESCRIPTION
**Pull request by lucab**
This updates to actix-0.10 and adapts the existing code to the new API.

### CODE REVIEW

**Review by travier — APPROVED** [review]
LGTM but I do not know actix/futures well enough to understand the new -> pin change.

**Comment by lucab** [comment]
> I do not know actix/futures well enough to understand the new -> pin change.

For reference, the change aligns to the new type constraints introduced with https://github.com/actix/actix/pull/355. In short, the new API requires that the future response chain can be pinned to a stable memory address, which we are upholding here.

**Comment by dustymabe** [comment]
can we merge this? The version of actix in Fedora is already at 0.10.0.

**Comment by lucab** [comment]
@dustymabe merged; do you need this quickly in a tagged release too?

**Comment by dustymabe** [comment]
I don't think so. We can easily patch the rpm.

**Pull request merged**
