### PR TITLE
cargo: update dependencies

### PR DESCRIPTION
**Pull request by HuijingHei**

### CODE REVIEW

**Comment by HuijingHei** [comment]
CI failed 
- error: package `clap_builder v4.5.2` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.71.0
- error: package `clap_derive v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.71.0

Should I update `rust-version = "1.71.0"` to `rust-version = "1.74.0"` in Cargo.toml?

**Comment by jlebon** [comment]
I think we can bump to 1.75.0. See https://github.com/coreos/coreos-installer/pull/1453.

**Comment by HuijingHei** [comment]
The failed log seems wired, run successfully locally, will look more about it.

**Comment by jlebon** [comment]
Possibly related to the zbus bump from 3.6 to 3.15. Odd that you can't reproduce it locally though. Are you sure that's with the same `Cargo.lock`?

**Comment by HuijingHei** [comment]
> Possibly related to the zbus bump from 3.6 to 3.15. Odd that you can't reproduce it locally though. Are you sure that's with the same `Cargo.lock`?

I rebuild with override/rootfs, can reproduce the failed issue locally, thanks!
```
# busctl call org.coreos.zincati /org/coreos/zincati org.coreos.zincati.Experimental LastRefreshTime
Call failed: The name is not activatable
```

**Comment by HuijingHei** [comment]
Thanks @jlebon for the pointer, see https://github.com/coreos/zincati/pull/1119#issuecomment-1802558737 and https://github.com/coreos/zincati/pull/966, will skip `zbus` update
```
qemu0 kola-runext-test-experimental.sh[2136]: # Call failed: The name is not activatable

qemu0 kola-runext-test-experimental.sh[2129]: + fatal 'File '\''err.txt'\'' doesn'\''t match regexp '\''Access denied'\'''

qemu0 kola-runext-test-experimental.sh[2129]: + echo error: File ''\''err.txt'\''' 'doesn'\''t' match regexp ''\''Access' 'denied'\'''

qemu0 kola-runext-test-experimental.sh[2129]: error: File 'err.txt' doesn't match regexp 'Access denied'

qemu0 kola-runext-test-experimental.sh[2129]: + exit 1
```

**Review by jlebon — APPROVED** [review]
LGTM. Though we should try to get to the bottom of that zbus issue at some point. Would be nice if we could stop bundling in Fedora, and I think this will likely be an issue.

**Review by c4rt0 — APPROVED** [review]
/lgtm

**Pull request merged**
